["Ayer pasé la noche soñando contigo. Me gustaría pasarme el día acurrucandome contigo. Buenos días.❤",
 "Buenos días bb. Espero y tengas un bonito día! Que la luz del sol en tu hermoso rostro te mantenga caliente si no estoy allí.❤",
 "Mi bebé. Quiero ser el único que esté en tu corazón por que tú tu solamente estás en el mío (ahora y para siempre). Estoy tan enamorado de ti que deseo dormir en tus brazos todas las noches y despertar abrazandote.❤",
 "Buenos días, mi amor!❤",
 "Buenos días princesa \ud83d\udc78. Te deseo un buen día. Haré que sea mejor aún.❤",
 "Buenos días bonita. Que la mañana sea tan brillante como tu sonrisa.❤",
 "Buenos días preciosa.❤",
 "Te amo no por lo que eres. Si no por lo que yo soy cuando estoy contigo. Buenos días mi lindo angel❤",
 "Estaba pensando en ti, y empecé a preguntarme desde hace cuanto tiempo estás en mi cabeza. Entonces me acordé: desde que te conocí. Lo mejor del día para ti bebé.❤",
 "Cuando abro los ojos todos los días todo lo que quiero ver es a ti. Buenos días, querida, te envíe abrazos y besos en mis pensamientos.❤",
 "Estar enamorado de ti hace que valga la pena levantarse cada mañana. Buenos días mi dulce corazón.❤",
 "Espero que sepas que cada vez que te digo que te cuides de camino a casa, te mantengas abrigada, tengas un buen día o duermas bien, lo que realmente digo es que te amo. Te amo tanto que estás empezando a robar el significado de otras palabras. Buenos días cariño.❤",
 "Eres mi mejor amiga, eres mi diario y mi otra mitad. Significas el mundo para mí y te amo. Buenos días bebé \ud83d\ude18 ",
 "Cuando digo que te amo más, no me refiero a que te amo más de lo que tu a mi. Quiero decir, te amo mas que a los malos días que tenemos por delante, te amo más que a cualquier pelea que podamos tener. Te amo más que la distancia entre nosotros, te amo más que cualquier obstaculo que pueda intentar interponerse entre nosotros. Te amo más. Que tengas un buen día por delante nena.❤",
 "Todos los días tienes algo nuevo que enseñarme, no quiero perderte. Buenos días encanto\ud83d\udc9f "]
